[build]
  publish = "dist"
  command = "npm run build"
  functions = ""

# Disable all extensions to prevent deployment hanging
[build.environment]
  NETLIFY_EXPERIMENTAL_BUILD_NODE_VERSION = "18"

# Asset-specific redirects - serve static files directly
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = false

[[redirects]]
  from = "/media/*"
  to = "/media/:splat"
  status = 200
  force = false

[[redirects]]
  from = "*.js"
  to = "/:splat"
  status = 200
  force = false

[[redirects]]
  from = "*.css"
  to = "/:splat"
  status = 200
  force = false

[[redirects]]
  from = "*.json"
  to = "/:splat"
  status = 200
  force = false

# SPA redirect - only for non-asset routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security headers with comprehensive CSP for Google Fonts and external resources
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://prod.spline.design https://generativelanguage.googleapis.com https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com data:; img-src 'self' data: https: blob: https://fonts.googleapis.com https://fonts.gstatic.com; media-src 'self' data: https: blob:; connect-src 'self' https://gjsektwcdvontsnyqobx.supabase.co https://generativelanguage.googleapis.com https://fonts.googleapis.com https://fonts.gstatic.com https://prod.spline.design https://unpkg.com https://cdn.jsdelivr.net wss: ws:; frame-src 'self' https://prod.spline.design; worker-src 'self' blob: https://prod.spline.design; child-src 'self' blob: https://prod.spline.design; manifest-src 'self';"

# Force correct MIME types for JavaScript files in assets/js/
[[headers]]
  for = "/assets/js/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Force correct MIME types for CSS files in assets/css/
[[headers]]
  for = "/assets/css/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Handle any remaining JS files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Handle any remaining CSS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

# Asset caching with proper types
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Image MIME types
[[headers]]
  for = "/assets/images/*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/images/*.webp"
  [headers.values]
    Content-Type = "image/webp"
    Cache-Control = "public, max-age=31536000, immutable"

# Root level images
[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Content-Type = "image/webp"
    Cache-Control = "public, max-age=31536000, immutable"

# Video MIME types
[[headers]]
  for = "/assets/videos/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/videos/*.webm"
  [headers.values]
    Content-Type = "video/webm"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webm"
  [headers.values]
    Content-Type = "video/webm"
    Cache-Control = "public, max-age=31536000, immutable"

# Service Worker with correct MIME type
[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"

# Manifest file
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400" 