// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjsektwcdvontsnyqobx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqc2VrdHdjZHZvbnRzbnlxb2J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODM1ODcsImV4cCI6MjA2MjU1OTU4N30.GCOueFVU9bWOXriqGrekpsyhvJ70SFg6l9j5BnEVRzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);